version: '3.3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - .:/home/jszkarlat/Development/ng-life-assistant/data
  life-assistant:
    depends_on:
      - mongo
    links:
      - mongo
    image: life-assistant:latest
    ports:
      - 3000:3000
    environment:
      - MONGODB_HOST=mongodb://mongo:27017/life-assistant
